-- Autogenerated by Luapress
local config = {
    -- Blog base url
    url = 'file:///home/nescivi/git/ssdn/ssdn_website/build',
--     url = 'https://www.sensestage.eu',
    -- Blog title
    title = 'Sense/Stage',
    -- Template name
    template = 'default',
    -- Posts per page
    posts_per_page = 3,
    -- Link directories not files
    link_dirs = false,
    -- Control the output directories for posts & pages
    pages_dir = nil,
    posts_dir = nil,
    -- Separator to put inside <a id="more"></a> link
    more_separator = '',
    -- Select a page as the landing page (optional, no path or suffix)
    index = 'home',
    print = true,
}

return config
